spring:
  application:
    name: transaction management
  datasource:
    url: jdbc:h2:mem:transactions
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
management:
  endpoint:
    health:
      probes:
        enabled: true
