apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-management
  template:
    metadata:
      labels:
        app: transaction-management
    spec:
      containers:
        - name: transaction-management
          image: transaction-management-spring:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
