# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: transaction-management-service
spec:
  selector:
    app: transaction-management
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort  # 或 LoadBalancer